version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: platzi .
    steps:
      - run:
          name: "Checking Versions"
          command: |
            node --version
            npm --version
