version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: node:8.0
    steps:
      - run:
          name: "Checking Versions"
          command: |
            node --version
            npm --version
